apiVersion: v1
kind: Pod
metadata:
  name: keylime-demo
spec:
  serviceAccount: keylime
  serviceAccountName: keylime
  sercurityContext: 
    runAsUser: root
  containers:
  - name: et-demo
    image: quay.io/astoycos/et-demo
    volumeMounts:
      - mountPath: "/sys/fs/cgroup"
        name: keylime-claim
    securityContext:
      privileged: true
  nodeSelector: 
    name: worker1
  volumes: 
    - name: keylime-claim
      persistentVolumeClaim:
        claimName: cgroup-vol-claim

